version: '3'
services:

  server:
    image: ghcr.io/guillaumedorschner/part-two-server:latest
    ports:
      - "80:80"
    depends_on:
      - db
  client:
    image: ghcr.io/guillaumedorschner/part-two-client:latest
    ports:
      - "3000:3000"
    depends_on:
      - server
    # interactive mode
    stdin_open: true
    tty: true
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    network_mode: "bridge"