name: Build and Publish to GHCR

on:
  push:
    paths:
      - 'Part 2 - Pake/**'
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./Part 2 - Pake
          file: ./Part 2 - Pake/Dockerfile
          push: true
          tags: ghcr.io/guillaumedorschner/part-two-server-flask:latest
