name: Release Package

on:
  push:
    branches:
      - main
    paths:
      - 'Part 2 - Pake/docker-compose.yml'
      - 'Part 2 - Pake/example.env'
      - 'Part 2 - Pake/init.sql'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release Package
        run: |
          mkdir release
          cp Part\ 2\ -\ Pake/example.env release/
          cp Part\ 2\ -\ Pake/init.sql release/
          cp Part\ 2\ -\ Pake/docker-compose.yml release/
          cd release
          zip -r release_package_part2.zip .

      - name: Upload Release Package
        uses: actions/upload-artifact@v2
        with:
          name: release-package-part2
          path: release/release_package_part2.zip
