name: Part 2 - Release Package

on:
  push:
    branches:
      - main
    paths:
      - 'Part 2 - Pake/docker-compose.yml'
      - 'Part 2 - Pake/example.env'
      - 'Part 2 - Pake/init.sql'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release Package
        run: |
          mkdir release
          cp Part\ 2\ -\ Pake/example.env release/
          cp Part\ 2\ -\ Pake/init.sql release/
          cp Part\ 2\ -\ Pake/docker-compose.yml release/
          cd release
          zip -r Part-two-PAKE.zip .

      - name: Upload Release Package
        uses: actions/upload-artifact@v2
        with:
          name: release-package-part2
          path: release/Part-two-PAKE.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v1.0.0"
          release_name: Release for commit ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/Part-two-PAKE.zip
          asset_name: Part-two-PAKE.zip
          asset_content_type: application/zip
